name: validations_generator
version: 1.0.0
description: Null-safety Generator for the validations package.
authors:
- Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/dartlib/validations.git

publish_to: none

environment:
  sdk: ">=3.0.0 <3.10.5"

dependencies:
  validations:
    path: ../validations
  analyzer: 5.12.0
#  build: '1.3.0'
#  build_config: '0.4.2'
  logging: 1.1.1
  source_gen: 1.3.0
  code_builder: 4.5.0
  dart_style: 2.3.0
  meta: 1.9.1

dev_dependencies:
  decimal: 2.3.2
  pedantic: 1.11.1
  test: 1.23.1
  build_runner: 2.3.3
  intl: 0.18.0
  build_test: 2.1.6
  collection: 1.17.1
